// Shown when the API is unreachable (e.g. a static-only deployment) so the
// curriculum still renders. The live backend always replaces this.
export const FALLBACK_CURRICULUM = [
  { module: { id: 'java', title: 'Java Foundations', subtitle: 'The language, JVM and tooling every backend engineer needs — from bytecode to virtual threads.', order: 1, color: '#f5a623', tech: ['JDK 21', 'JVM', 'Maven', 'Concurrency'], lessonCount: 12, minutes: 196 }, lessons: [] },
  { module: { id: 'spring-core', title: 'Spring Core & Framework', subtitle: 'IoC, dependency injection, AOP, events and transactions — the engine under every Spring app.', order: 2, color: '#6fce6f', tech: ['IoC', 'DI', 'AOP', 'Events', 'Transactions'], lessonCount: 9, minutes: 156 }, lessons: [] },
  { module: { id: 'spring-boot', title: 'Spring Boot', subtitle: 'Auto-configuration, REST APIs, Spring Data JPA, testing, Actuator and production readiness.', order: 3, color: '#4cc2ff', tech: ['Auto-configuration', 'REST', 'JPA', 'Testing', 'Actuator'], lessonCount: 9, minutes: 156 }, lessons: [] },
  { module: { id: 'spring-security', title: 'Spring Security', subtitle: 'Authentication, JWT, authorization, OAuth2 and hardening APIs the way production teams do.', order: 4, color: '#ff6b6b', tech: ['Filter Chain', 'JWT', 'OAuth2', 'Method Security'], lessonCount: 9, minutes: 150 }, lessons: [] },
  { module: { id: 'spring-ai', title: 'Spring AI', subtitle: 'ChatClient, embeddings, RAG and function calling — production patterns for AI-powered backends.', order: 5, color: '#bb9af7', tech: ['ChatClient', 'Embeddings', 'RAG', 'Function Calling'], lessonCount: 8, minutes: 132 }, lessons: [] },
  { module: { id: 'capstone', title: 'Capstone: Full Backend Project', subtitle: 'A complete, runnable payments API built with everything above — layered architecture, JWT security, tests.', order: 6, color: '#2ac3de', tech: ['Spring Boot', 'JPA', 'Security', 'JUnit'], lessonCount: 5, minutes: 84 }, lessons: [] },
  { module: { id: 'spring-cloud', title: 'Spring Cloud & Microservices', subtitle: 'Service discovery, centralized config, API gateway, Resilience4j and distributed tracing — with a runnable 5-service demo.', order: 7, color: '#7aa2f7', tech: ['Eureka', 'Config Server', 'Gateway', 'Resilience4j', 'Tracing'], lessonCount: 7, minutes: 138 }, lessons: [] },
  { module: { id: 'spring-kafka', title: 'Spring Kafka & Event-Driven Messaging', subtitle: 'Kafka producers and listeners, consumer groups, the transactional outbox, retries and DLQs — with a runnable outbox demo.', order: 8, color: '#f7768e', tech: ['Kafka', 'Outbox', 'Consumer Groups', 'DLQ', 'Retry'], lessonCount: 7, minutes: 140 }, lessons: [] },
  { module: { id: 'spring-webflux', title: 'Spring WebFlux & Reactive', subtitle: 'Reactive programming with Mono and Flux, non-blocking WebClient, R2DBC data access and when reactive beats servlet — with a runnable demo.', order: 9, color: '#9ece6a', tech: ['Mono', 'Flux', 'WebClient', 'R2DBC', 'Netty'], lessonCount: 7, minutes: 130 }, lessons: [] },
];
